version: "3"

volumes:
  attendance_local_postgres_data: {}
  attendance_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: attendance_local_django
    container_name: attendance_local_django
    depends_on:
      - postgres
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: attendance_production_postgres
    container_name: attendance_local_postgres
    volumes:
      - attendance_local_postgres_data:/var/lib/postgresql/data
      - attendance_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: axllent/mailpit:v1.8
    container_name: attendance_local_mailpit
    ports:
      - "8025:8025"
