# Generated by Django 4.2.5 on 2023-10-01 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("challenge_solved", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "face_recognition_status",
                    models.CharField(
                        choices=[("PROCESSING", "Processing"), ("SUCCESS", "Success"), ("FAILURE", "Failure")],
                        default="PROCESSING",
                        max_length=12,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("salt", models.CharField(default="69b414dd115b476ebeb8759be68e0d73", editable=False, max_length=32)),
                ("course_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.course")),
            ],
        ),
    ]
