# Generated by Django 4.2.5 on 2023-10-01 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="teacher_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="attendance",
            name="session_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.session"),
        ),
        migrations.AddField(
            model_name="attendance",
            name="student_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("name", "teacher_id")},
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("session_id", "student_id")},
        ),
    ]
