# Generated by Django 4.2.5 on 2023-10-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_attendance_face_recognition_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="challenge_solved",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="face_recognition_status",
            field=models.CharField(
                choices=[
                    ("INITIALIZE", "Initialize"),
                    ("PROCESSING", "Processing"),
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                ],
                default="INITIALIZE",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="salt",
            field=models.CharField(default="3c400ee1341f47f99d4b7788403dfef5", editable=False, max_length=32),
        ),
    ]
