# Generated by Django 4.2.5 on 2023-10-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_attendance_face_image_alter_session_salt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="face_recognition_status",
            field=models.CharField(
                choices=[
                    ("INITIALIZE", "Initialize"),
                    ("PROCESSING", "Processing"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                default="INITIALIZE",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="salt",
            field=models.CharField(default="b17f287c6b6f40e9bc619a5836628ac7", editable=False, max_length=32),
        ),
    ]
