# Generated by Django 4.2.5 on 2023-10-05 21:37

from django.db import migrations, models
import attendance.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_attendance_challenge_solved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="face_image",
            field=models.ImageField(null=True, upload_to=attendance.core.models.get_face_image_path),
        ),
        migrations.AlterField(
            model_name="session",
            name="salt",
            field=models.CharField(default="0a000e6357344aaca780f66ccbb8e1b2", editable=False, max_length=32),
        ),
    ]
